spring.application.name=expense-tracker
server.port=8080

# V1 intentionally uses H2 so MySQL is not required.
# We will introduce MySQL through Docker in a later version.
spring.datasource.url=jdbc:h2:file:./data/expense_tracker
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.cache=false
