apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todo-app

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mysql-init-configmap.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - frontend-ingress.yaml
