package com.prem.fileapp;
import org.springframework.web.bind.annotation.*;import org.springframework.http.*;import org.springframework.security.crypto.password.PasswordEncoder;import jakarta.servlet.http.*;import java.security.*;import java.nio.charset.StandardCharsets;import java.time.Instant;import java.util.*;import org.springframework.beans.factory.annotation.Value;
@RestController @RequestMapping("/api/auth") public class AuthController{
 private final UserRepo users;private final RefreshRepo refresh;private final PasswordEncoder enc;private final JwtService jwt;private final boolean secure;
 public AuthController(UserRepo u,RefreshRepo r,PasswordEncoder e,JwtService j,@Value("${security.refresh-cookie.secure:false}")boolean s){users=u;refresh=r;enc=e;jwt=j;secure=s;}
 record Cred(String username,String password){} 
 @PostMapping("/register") public Map<String,String> register(@RequestBody Cred c){String n=c.username().trim().toLowerCase();if(c.password()==null||c.password().length()<8)throw new IllegalArgumentException("Password must contain at least 8 characters.");if(users.findByUsername(n).isPresent())throw new IllegalArgumentException("Username already exists.");User u=new User();u.username=n;u.passwordHash=enc.encode(c.password());users.save(u);return Map.of("message","Registered successfully.");}
 @PostMapping("/login") public Map<String,Object> login(@RequestBody Cred c,HttpServletResponse res){User u=users.findByUsername(c.username().trim().toLowerCase()).orElseThrow(()->new IllegalArgumentException("Invalid username or password."));if(!enc.matches(c.password(),u.passwordHash))throw new IllegalArgumentException("Invalid username or password.");return issue(u,UUID.randomUUID().toString(),res);}
 @PostMapping("/refresh") public Map<String,Object> refresh(@CookieValue(value="refreshToken",required=false)String raw,HttpServletResponse res){if(raw==null)throw new IllegalArgumentException("Refresh token missing.");RefreshToken old=refresh.findByTokenHash(hash(raw)).orElseThrow(()->new IllegalArgumentException("Invalid refresh token."));if(old.revoked){refresh.findByFamilyId(old.familyId).forEach(x->{x.revoked=true;refresh.save(x);});throw new IllegalArgumentException("Refresh token reuse detected.");}if(old.expiresAt.isBefore(Instant.now()))throw new IllegalArgumentException("Refresh token expired.");old.revoked=true;refresh.save(old);User u=users.findById(old.userId).orElseThrow(()->new IllegalArgumentException("User not found."));return issue(u,old.familyId,res);}
 @PostMapping("/logout") public Map<String,String> logout(@CookieValue(value="refreshToken",required=false)String raw,HttpServletResponse res){if(raw!=null)refresh.findByTokenHash(hash(raw)).ifPresent(x->{x.revoked=true;refresh.save(x);});cookie(res,"",0);return Map.of("message","Logged out.");}
 @GetMapping("/me") public Map<String,String> me(org.springframework.security.core.Authentication a){User u=users.findById(a.getName()).orElseThrow();return Map.of("id",u.id,"username",u.username,"role",u.role);}
 private Map<String,Object> issue(User u,String family,HttpServletResponse res){String access=jwt.create(u);byte[] b=new byte[48];new SecureRandom().nextBytes(b);String raw=Base64.getUrlEncoder().withoutPadding().encodeToString(b);RefreshToken x=new RefreshToken();x.userId=u.id;x.tokenHash=hash(raw);x.familyId=family;x.createdAt=Instant.now();x.expiresAt=Instant.now().plusSeconds(604800);refresh.save(x);cookie(res,raw,604800);return Map.of("accessToken",access,"expiresIn",900);}
 private void cookie(HttpServletResponse r,String v,int age){Cookie c=new Cookie("refreshToken",v);c.setHttpOnly(true);c.setSecure(secure);c.setPath("/api/auth");c.setMaxAge(age);c.setAttribute("SameSite","Lax");r.addCookie(c);}
 private String hash(String v){try{return Base64.getUrlEncoder().withoutPadding().encodeToString(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
