apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: todo-app
type: Opaque
stringData:
  MYSQL_DATABASE: todo_db
  MYSQL_USER: todo_user
  MYSQL_PASSWORD: todo_password
  MYSQL_ROOT_PASSWORD: root_password
