import{useMemo,useState}from'react';import{useRoadmap}from'./hooks/useRoadmap';import ProgressHeader from'./components/ProgressHeader';import TopicModal from'./components/TopicModal';import MockInterview from'./components/MockInterview';import'./styles/app.css';
const routine=[['applications','Job applications',30,'Send 3–5 targeted applications.'],['prep','Interview preparation',60,'Study + speak answers aloud.'],['project','Project implementation',45,'Build one production-quality feature.'],['freelance','Freelancing pipeline',30,'Send 2–3 proposals/follow-ups.']];
const stack=['Java','Spring Boot','React + Vite','MongoDB','JWT','Redis','Kafka','Docker','Kubernetes','AWS','System Design'];
export default function App(){const{phases,progress,loading,save}=useRoadmap();const[search,setSearch]=useState(''),[filter,setFilter]=useState('all'),[phase,setPhase]=useState('all'),[selected,setSelected]=useState(null),[timer,setTimer]=useState(0);const st=progress.status||{},notes=progress.notes||{},rs=progress.routine||{};
const topics=phases.flatMap(p=>(p.topics||[]).map(t=>({...t,phase:p.title||p.name})));const done=topics.filter(t=>st[t.topicId]==='done').length,pct=topics.length?Math.round(done/topics.length*100):0,mins=topics.filter(t=>st[t.topicId]==='done').reduce((n,t)=>n+(t.minutes||20),0);
const patch=x=>save({...progress,...x});const cycle=id=>{const s=st[id]||'todo';patch({status:{...st,[id]:s==='todo'?'progress':s==='progress'?'done':'todo'}})};
const filtered=useMemo(()=>phases.map(p=>({...p,topics:(p.topics||[]).filter(t=>{const text=(t.title+' '+(t.summary||'')+' '+(t.questions||[]).join(' ')).toLowerCase(),s=st[t.topicId]||'todo';const f=filter==='all'||filter===s||(filter==='hard'&&t.difficulty==='hard')||(filter==='easy'&&t.difficulty==='easy');return(!search||text.includes(search.toLowerCase()))&&f})})).filter(p=>p.topics.length&&(phase==='all'||String(p.phaseId)===phase)),[phases,search,filter,phase,st]);
const today=topics.find(t=>st[t.topicId]!=='done')||topics[0];const startTimer=m=>{setTimer(m*60);const id=setInterval(()=>setTimer(v=>{if(v<=1){clearInterval(id);return 0}return v-1}),1000)};
const exportData=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(progress,null,2)],{type:'application/json'}));a.download='interview-roadmap-progress.json';a.click()};
if(loading)return <div className="loading">Loading roadmap…</div>;
return <><ProgressHeader pct={pct} done={done} total={topics.length} mins={mins} mock={progress.mockScore} onExport={exportData}/><main className="container">
<section className="hero-grid"><div className="card"><span className="label">Today's Focus</span><h2>{today?.title}</h2><p>{today?.summary||'Interview preparation topic'}</p><button className="primary" onClick={()=>startTimer(today?.minutes||20)}>Start {today?.minutes||20} min timer</button> <button onClick={()=>cycle(today.topicId)}>Mark done</button></div><div className="card"><span className="label">Study Timer</span><h2>{String(Math.floor(timer/60)).padStart(2,'0')}:{String(timer%60).padStart(2,'0')}</h2><p>Focused study countdown.</p></div></section>
<section className="card controls"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search topics, questions..."/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All</option><option value="todo">Not started</option><option value="progress">In progress</option><option value="done">Completed</option><option value="hard">Hard</option><option value="easy">Easy</option></select><select value={phase} onChange={e=>setPhase(e.target.value)}><option value="all">All phases</option>{phases.map(p=><option key={p.phaseId} value={p.phaseId}>{p.title||p.name}</option>)}</select></section>
<section className="phase-list">{filtered.map(p=><article className="card" key={p.phaseId}><div className="phase-head"><div><span className="phase-number">Phase {p.phaseId}</span><h2>{p.title||p.name}</h2><p>{p.description}</p></div><strong>{Math.round(p.topics.filter(t=>st[t.topicId]==='done').length/p.topics.length*100)}%</strong></div><div className="mini-progress"><span style={{width:`${p.topics.filter(t=>st[t.topicId]==='done').length/p.topics.length*100}%`}}/></div><div className="topic-list">{p.topics.map(t=><div className={'topic '+(st[t.topicId]==='done'?'done':'')} key={t.topicId}><button className="check" onClick={()=>cycle(t.topicId)}>{st[t.topicId]==='done'?'✓':st[t.topicId]==='progress'?'•':''}</button><div className="topic-main" onClick={()=>setSelected({...t,phase:p.title||p.name,note:notes[t.topicId]||''})}><div className="topic-title"><strong>{t.title}</strong><span className={'difficulty '+t.difficulty}>{t.difficulty}</span><span className="mins">{t.minutes}m</span></div><p>{t.summary}</p></div><button className="notes-btn" onClick={()=>setSelected({...t,phase:p.title||p.name,note:notes[t.topicId]||''})}>Details →</button></div>)}</div></article>)}</section>
<section className="lower-grid"><div className="card"><span className="label">Daily Routine</span><h2>Small consistent output</h2>{routine.map(([id,title,min,desc])=><label className="routine-item" key={id}><input type="checkbox" checked={!!rs[id]} onChange={()=>patch({routine:{...rs,[id]:!rs[id]}})}/><span><strong>{title}</strong><small>{min} min · {desc}</small></span></label>)}</div><div className="card"><span className="label">Capstone Stack</span><h2>Production-ready evolution</h2><div className="stack">{stack.map(x=><span key={x}>{x}</span>)}</div></div></section>
<MockInterview onScore={score=>patch({mockScore:score})}/></main>{selected&&<TopicModal topic={selected} onClose={()=>setSelected(null)} onStatus={cycle} onNote={(id,n)=>patch({notes:{...notes,[id]:n}})}/>}</>}
